/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musabbiha.Frame;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import musabbiha.Classes.*;

import javax.swing.table.DefaultTableModel;
import static musabbiha.Frame.fDashboard.maximize;

/**
 *
 * @author hp
 */
public class fSearch extends javax.swing.JFrame {

    /**
     * Creates new form SearchByFile
     */
    int FileStatus;
    int FolderStatus;
    int userID;
    File file = new File("");
            
    public fSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnMin3 = new javax.swing.JButton();
        btnMaxMin3 = new javax.swing.JButton();
        btnExit3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnMin3.setBackground(new java.awt.Color(204, 204, 204));
        btnMin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/minimize1.png"))); // NOI18N
        btnMin3.setContentAreaFilled(false);

        btnMaxMin3.setBackground(new java.awt.Color(204, 204, 204));
        btnMaxMin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/add.png"))); // NOI18N
        btnMaxMin3.setContentAreaFilled(false);

        btnExit3.setBackground(new java.awt.Color(255, 102, 102));
        btnExit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/cancel.png"))); // NOI18N
        btnExit3.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaxMin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMaxMin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnMin3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnExit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtsearch.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtsearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GO");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblSearch.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tblSearch.setForeground(new java.awt.Color(102, 102, 102));
        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""}
            },
            new String [] {
                ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearch.setGridColor(new java.awt.Color(204, 204, 204));
        tblSearch.setOpaque(false);
        tblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearch);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsearch)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CSQL sss = new CSQL();
        sss.connection();
        if(FileStatus==1){
            sss.searchfile(txtsearch.getText(), this,userID);
        }
        else if(FolderStatus==1){
            sss.searchfolder(txtsearch.getText(), this,userID);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchMouseClicked
        DefaultTableModel tbl = (DefaultTableModel) tblSearch.getModel();
        
        Vector v = new Vector();
        CSQL s = new CSQL();
        s.connection();
                
        int row = tblSearch.getSelectedRow();
        
        if(FileStatus==1){
            s.OpenFile(tbl.getValueAt(row, 0).toString(),file,userID);
            s.UpdateFileLog(s.GetFileID(tbl.getValueAt(row, 0).toString(), userID));
           
        }
        else if(FolderStatus==1){
            v = s.openFolder(tbl.getValueAt(row, 0).toString(),userID); 
        }
        
        
        if(v.size()!=0){
            
            fFile f = new fFile();
            DefaultTableModel tbl2 = (DefaultTableModel) f.tblFile.getModel();
            
            for (int i = 0; i < v.size(); i++) {
            tbl2.addRow((Object[]) v.elementAt(i));
            }
            f.setVisible(true);
            f.setLocationRelativeTo(null);
            
        }else {
            JOptionPane.showConfirmDialog(null, "NO FILE FOUNDS IN THIS FOLDER...");
        }
        
    }//GEN-LAST:event_tblSearchMouseClicked

     private void btnMin3MouseEntered(java.awt.event.MouseEvent evt) {                                     
        btnMin3.setOpaque(true);
    }                                    

    private void btnMin3MouseExited(java.awt.event.MouseEvent evt) {                                    
        btnMin3.setOpaque(false);
    }                                   

    private void btnMin3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        this.setState(Frame.ICONIFIED);
    }                                    

    private void btnMaxMin3MouseEntered(java.awt.event.MouseEvent evt) {                                        
        btnMaxMin3.setOpaque(true);
    }                                       

    private void btnMaxMin3MouseExited(java.awt.event.MouseEvent evt) {                                       
        btnMaxMin3.setOpaque(false);
    }                                      

    private void btnMaxMin3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        if(maximize){
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment evn = GraphicsEnvironment.getLocalGraphicsEnvironment();
            this.setMaximizedBounds(evn.getMaximumWindowBounds());
            maximize = false;
        }
        else{
            setExtendedState(JFrame.NORMAL);
            maximize = true;
        }
    }                                       

    private void btnExit3MouseExited(java.awt.event.MouseEvent evt) {                                     
        
        btnExit3.setOpaque(false);
    }                                    

    private void btnExit3MouseEntered(java.awt.event.MouseEvent evt) {                                      
        btnExit3.setOpaque(true);
    }                                     

    private void btnExit3MouseClicked(java.awt.event.MouseEvent evt) {                                      
        this.dispose();
    }                       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit3;
    private javax.swing.JButton btnMaxMin3;
    private javax.swing.JButton btnMin3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
