package musabbiha.Frame;

import musabbiha.Classes.CSQL;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import musabbiha.Classes.EmailConnection;
import static musabbiha.Frame.fDashboard.maximize;

public class fSignup extends javax.swing.JFrame {

    byte[] sqlImage, tempImage;
    JFileChooser jFileChooser1 = new JFileChooser();
    
    public fSignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMin2 = new javax.swing.JButton();
        btnMaxMin2 = new javax.swing.JButton();
        btnExit2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        profileImage = new javax.swing.JLabel();
        btnUpload = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnMin3 = new javax.swing.JButton();
        btnMaxMin3 = new javax.swing.JButton();
        btnExit3 = new javax.swing.JButton();
        goBack = new javax.swing.JLabel();

        btnMin2.setBackground(new java.awt.Color(255, 255, 255));
        btnMin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/minimize1.png"))); // NOI18N
        btnMin2.setContentAreaFilled(false);
        btnMin2.setOpaque(true);

        btnMaxMin2.setBackground(new java.awt.Color(255, 255, 255));
        btnMaxMin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/add.png"))); // NOI18N
        btnMaxMin2.setContentAreaFilled(false);
        btnMaxMin2.setOpaque(true);

        btnExit2.setBackground(new java.awt.Color(255, 255, 255));
        btnExit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/cancel.png"))); // NOI18N
        btnExit2.setContentAreaFilled(false);
        btnExit2.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("DMS Sign up");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Please enter required information :)");

        jLabel3.setBackground(new java.awt.Color(255, 204, 153));
        jLabel3.setOpaque(true);

        profileImage.setBackground(new java.awt.Color(102, 102, 102));
        profileImage.setBorder(new javax.swing.border.MatteBorder(null));
        profileImage.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileImage, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        btnUpload.setBackground(new java.awt.Color(0, 0, 0));
        btnUpload.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnUpload.setForeground(new java.awt.Color(255, 255, 255));
        btnUpload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpload.setText("UPLOAD");
        btnUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpload.setOpaque(true);
        btnUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUploadMouseClicked(evt);
            }
        });

        btnContinue.setBackground(new java.awt.Color(255, 204, 153));
        btnContinue.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(255, 255, 255));
        btnContinue.setText("CONTINUE");
        btnContinue.setContentAreaFilled(false);
        btnContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinue.setOpaque(true);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(102, 102, 102));
        txtName.setText("ENTER YOUR FULL NAME");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
        });
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setText("ENTER YOUR EMAIL");
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(102, 102, 102));
        txtAddress.setText("ENTER YOUR ADDRESS");
        txtAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddressMouseClicked(evt);
            }
        });

        txtNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtNumber.setForeground(new java.awt.Color(102, 102, 102));
        txtNumber.setText("ENTER YOUR CONTACT NUMBER");
        txtNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumberMouseClicked(evt);
            }
        });
        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setText("ENTER YOUR PASSWORD");
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addComponent(txtName)
                                    .addComponent(txtAddress)
                                    .addComponent(txtNumber)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(143, 143, 143)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                            .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnMin3.setBackground(new java.awt.Color(204, 204, 204));
        btnMin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/minimize1.png"))); // NOI18N
        btnMin3.setContentAreaFilled(false);
        btnMin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMin3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMin3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMin3MouseExited(evt);
            }
        });

        btnMaxMin3.setBackground(new java.awt.Color(204, 204, 204));
        btnMaxMin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/add.png"))); // NOI18N
        btnMaxMin3.setContentAreaFilled(false);
        btnMaxMin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaxMin3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaxMin3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaxMin3MouseExited(evt);
            }
        });

        btnExit3.setBackground(new java.awt.Color(204, 204, 204));
        btnExit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/cancel.png"))); // NOI18N
        btnExit3.setContentAreaFilled(false);
        btnExit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExit3MouseExited(evt);
            }
        });

        goBack.setBackground(new java.awt.Color(204, 204, 204));
        goBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/left-arrow.png"))); // NOI18N
        goBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMaxMin3)
                .addGap(13, 13, 13)
                .addComponent(btnExit3)
                .addGap(1, 1, 1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMaxMin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMin3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(goBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        if(confirm()==true){
            System.out.println("sb thk h");
            CSQL s = new CSQL();
            s.connection();
            if(!s.checkEmail(txtEmail.getText())){
            EmailConnection em = new EmailConnection();
            int x = (int)(Math.random()*((1000000-1)+1))+1;
            if(em.email(this.txtEmail.getText(),Integer.toString(x))){
            String Code = JOptionPane.showInputDialog("ENTER CODE:");
            int x2 = Integer.parseInt(Code);
            if(x2==x){
                JOptionPane.showMessageDialog(null, "YOU ARE UP!");
                s.signup(this.txtName.getText(), this.txtEmail.getText(), this.txtNumber.getText(), this.txtPassword.getText(), this.txtAddress.getText(), sqlImage);
            }
         }
            
        }else{
                JOptionPane.showMessageDialog(null, "SAME EMAIL EXISTS");
            }
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        txtName.selectAll();
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        txtEmail.selectAll();
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddressMouseClicked
        txtAddress.selectAll();
    }//GEN-LAST:event_txtAddressMouseClicked

    private void txtNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumberMouseClicked
        txtNumber.selectAll();
    }//GEN-LAST:event_txtNumberMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        txtPassword.selectAll();
    }//GEN-LAST:event_txtPasswordMouseClicked
public ImageIcon ResizeImage(String ImagePath){
        ImageIcon i = new ImageIcon(new ImageIcon(ImagePath).getImage().getScaledInstance(this.profileImage.getWidth(),this.profileImage.getHeight(), Image.SCALE_SMOOTH));
        return i;
    }
    private void btnUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadMouseClicked
         jFileChooser1.setVisible(true);
         
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        jFileChooser1.addChoosableFileFilter(filter);
        int result = jFileChooser1.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            try {
                File selectedFile = jFileChooser1.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
            profileImage.setIcon(ResizeImage(path));
                
                File file = new File(path);
                FileInputStream f;
                f = new FileInputStream(file);
                ByteArrayOutputStream b = new ByteArrayOutputStream();
                byte[] buff = new byte[1024];
                for(int a ; (a=f.read(buff))!=-1;)
                {
                    b.write(buff, 0, a);
                }
               byte[] rimage = b.toByteArray();
               this.sqlImage=rimage;
                System.out.println(sqlImage);
//            rimage = path;
            } catch (IOException ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }

        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("YOU CANCLED!");
        }
        this.setVisible(true);
    }//GEN-LAST:event_btnUploadMouseClicked

    
    
    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        txtName.selectAll();
    }//GEN-LAST:event_txtNameFocusGained

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        if(txtEmail.getText().equals("ENTER YOUR EMAIL"))
        txtEmail.selectAll();
    }//GEN-LAST:event_txtEmailKeyPressed

    private void goBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseEntered
        goBack.setOpaque(true);
    }//GEN-LAST:event_goBackMouseEntered

    private void goBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseExited
        goBack.setOpaque(false);
    }//GEN-LAST:event_goBackMouseExited

    private void goBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseClicked
        this.dispose();
        fLogin f = new fLogin();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_goBackMouseClicked

    private void btnMin3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMin3MouseEntered
        btnMin3.setOpaque(true);
    }//GEN-LAST:event_btnMin3MouseEntered

    private void btnMin3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMin3MouseExited
        btnMin3.setOpaque(false);
    }//GEN-LAST:event_btnMin3MouseExited

    private void btnMin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMin3MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMin3MouseClicked

    private void btnMaxMin3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMin3MouseEntered
        btnMaxMin3.setOpaque(true);
    }//GEN-LAST:event_btnMaxMin3MouseEntered

    private void btnMaxMin3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMin3MouseExited
        btnMaxMin3.setOpaque(false);
    }//GEN-LAST:event_btnMaxMin3MouseExited

    private void btnMaxMin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMin3MouseClicked
        if(maximize){
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment evn = GraphicsEnvironment.getLocalGraphicsEnvironment();
            this.setMaximizedBounds(evn.getMaximumWindowBounds());
            maximize = false;
        }
        else{
            setExtendedState(JFrame.NORMAL);
            maximize = true;
        }
    }//GEN-LAST:event_btnMaxMin3MouseClicked

    private void btnExit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit3MouseExited
        
        btnExit3.setOpaque(false);
    }//GEN-LAST:event_btnExit3MouseExited

    private void btnExit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit3MouseEntered
        btnExit3.setOpaque(true);
    }//GEN-LAST:event_btnExit3MouseEntered

    private void btnExit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit3MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExit3MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fSignup().setVisible(true);
            }
        });
    }
    
    public boolean confirm(){
        if(nameCheck()==false){
            JOptionPane.showMessageDialog(null, "ENTER NAME!");
            return false;
        }
        
        if(addressCheck()==false){
            JOptionPane.showMessageDialog(null, "ENTER ADDRESS!");
            return false;
        }
        
        if(numberCheck()==false){
            JOptionPane.showMessageDialog(null, "ENTER NUMBER!");
            return false;
        }
        
        if(passwordCheck()==false){
            JOptionPane.showMessageDialog(null, "ENTER PASSWORD!");
            return false;
        }
        
        if(emailCheck()==false){
            JOptionPane.showMessageDialog(null, "ENTER EMAIL!");
            return false;
        }
        return true;
    }
    public boolean nameCheck(){
        if(txtName.getText().equals("")||txtName.getText().equals("ENTER YOUR FULL NAME")){
            System.out.println("name ghlt h");
            return false;
        }
        else{
            return true;
        }
    }
    
    public boolean emailCheck(){
        if(txtEmail.getText().equals("")||txtEmail.getText().equals("ENTER YOUR EMAIL")){
            System.out.println("emaail ghlt h");
            return false;
        }
        else{
            return true;
        }
    }
    
    public boolean addressCheck(){
        if(txtAddress.getText().equals("")||txtAddress.getText().equals("ENTER YOUR ADDRESS")){
            System.out.println("address ghlt h");
            return false;
        }
        else{
            return true;
        }
    }
    
    public boolean numberCheck(){
        if(txtNumber.getText().equals("")|| txtNumber.getText().equals("ENTER YOUR CONTACT NUMBER")){
            System.out.println("num ghlt h");
            return false;
        }
        else{
            return true;
        }
    }
    
    public boolean passwordCheck(){
        if(txtPassword.getText().equals("")||txtPassword.getText().equals("ENTER YOUR PASSWORD")){
            System.out.println("password ghlt h");
            return false;
        }
        else{
            return true;
        }
    }

//    public ImageIcon ResizeImage(String ImagePath){
//        ImageIcon i = new ImageIcon(new ImageIcon(ImagePath).getImage().getScaledInstance(image.getWidth(),image.getHeight(), Image.SCALE_SMOOTH));
//        return i;
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnExit2;
    private javax.swing.JButton btnExit3;
    private javax.swing.JButton btnMaxMin2;
    private javax.swing.JButton btnMaxMin3;
    private javax.swing.JButton btnMin2;
    private javax.swing.JButton btnMin3;
    private javax.swing.JLabel btnUpload;
    private javax.swing.JLabel goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel profileImage;
    public javax.swing.JTextField txtAddress;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtNumber;
    public javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
