/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musabbiha.Frame;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import musabbiha.Classes.CSQL;

/**
 *
 * @author me
 */
public class fUserDetail extends javax.swing.JFrame {

    public int UserID;
    public String password;
    CSQL s;
    /**
     * Creates new form fUserDetail
     */
    public fUserDetail() {
        initComponents();
        s = new CSQL();
        s.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        lblUserNumber = new javax.swing.JLabel();
        lblUserAddress = new javax.swing.JLabel();
        editUserName = new javax.swing.JLabel();
        editUserEmail = new javax.swing.JLabel();
        editUserNumber = new javax.swing.JLabel();
        editUserAddress = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblDp = new javax.swing.JLabel();
        lblDeleteDp = new javax.swing.JLabel();
        lblEditDp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNumberOfFiles = new javax.swing.JLabel();
        lblNumberOfFolders = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Name");

        jLabel2.setText("Email");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Address");

        lblUserName.setText("jLabel5");

        lblUserEmail.setText("jLabel6");

        lblUserNumber.setText("jLabel7");

        lblUserAddress.setText("jLabel8");

        editUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/edit.png"))); // NOI18N
        editUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editUserNameMouseClicked(evt);
            }
        });

        editUserEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/edit.png"))); // NOI18N
        editUserEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editUserEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editUserEmailMouseClicked(evt);
            }
        });

        editUserNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/edit.png"))); // NOI18N
        editUserNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editUserNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editUserNumberMouseClicked(evt);
            }
        });

        editUserAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/edit.png"))); // NOI18N
        editUserAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editUserAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editUserAddressMouseClicked(evt);
            }
        });

        btnChangePassword.setText("Change Password");
        btnChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangePasswordMouseClicked(evt);
            }
        });

        lblDp.setBackground(new java.awt.Color(0, 0, 0));
        lblDp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDp.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDp, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDp, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        lblDeleteDp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/cross.png"))); // NOI18N
        lblDeleteDp.setText("Delete");
        lblDeleteDp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDeleteDp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteDpMouseClicked(evt);
            }
        });

        lblEditDp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musabbiha/icon/edit.png"))); // NOI18N
        lblEditDp.setText("Edit");
        lblEditDp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditDp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditDpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChangePassword))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDeleteDp)
                                    .addComponent(lblEditDp))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUserAddress))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUserNumber))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUserEmail))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(145, 145, 145)
                                        .addComponent(lblUserName)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editUserName)
                                    .addComponent(editUserAddress)
                                    .addComponent(editUserNumber)
                                    .addComponent(editUserEmail))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDeleteDp)
                        .addGap(18, 18, 18)
                        .addComponent(lblEditDp)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUserName)
                    .addComponent(editUserName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUserEmail)
                    .addComponent(editUserEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblUserNumber)
                    .addComponent(editUserNumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblUserAddress)
                    .addComponent(editUserAddress))
                .addGap(58, 58, 58)
                .addComponent(btnChangePassword)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Account Information", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Number of Files");

        jLabel6.setText("Number of Folders");

        lblNumberOfFiles.setText("jLabel7");
        lblNumberOfFiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblNumberOfFolders.setText("jLabel8");
        lblNumberOfFolders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(155, 155, 155)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberOfFolders)
                    .addComponent(lblNumberOfFiles))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNumberOfFiles))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblNumberOfFolders))
                .addContainerGap(484, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cabinet Information", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Account Information");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUserNameMouseClicked
        String Edit = JOptionPane.showInputDialog(null, "Enter new name!");
        if(!Edit.equals(null)){
        s.editName(Edit, UserID);
        }
    }//GEN-LAST:event_editUserNameMouseClicked

    private void editUserEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUserEmailMouseClicked
        
        
    }//GEN-LAST:event_editUserEmailMouseClicked

    private void editUserNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUserNumberMouseClicked
        String Edit = JOptionPane.showInputDialog(null, "Enter new number!");
        if(!Edit.equals(null)){
        s.editNumber(Edit, UserID);
        }
    }//GEN-LAST:event_editUserNumberMouseClicked

    private void editUserAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUserAddressMouseClicked
        String Edit = JOptionPane.showInputDialog(null, "Enter new address!");
        if(!Edit.equals(null)){
        s.editAddress(Edit, UserID);
        }
    }//GEN-LAST:event_editUserAddressMouseClicked

    private void btnChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePasswordMouseClicked
        String Check = JOptionPane.showInputDialog(null, "Enter old password!");
        if(!Check.equals(null)){
        if(Check.equals(password)){
            String Edit = JOptionPane.showInputDialog(null, "Enter new password!");
            s.editPasswordUserID(Edit, UserID);
        }
        }
    }//GEN-LAST:event_btnChangePasswordMouseClicked

    private void lblDeleteDpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteDpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDeleteDpMouseClicked

    private void lblEditDpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditDpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEditDpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fUserDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fUserDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fUserDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fUserDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fUserDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JLabel editUserAddress;
    private javax.swing.JLabel editUserEmail;
    private javax.swing.JLabel editUserName;
    private javax.swing.JLabel editUserNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lblDeleteDp;
    public javax.swing.JLabel lblDp;
    public javax.swing.JLabel lblEditDp;
    public javax.swing.JLabel lblNumberOfFiles;
    public javax.swing.JLabel lblNumberOfFolders;
    public javax.swing.JLabel lblUserAddress;
    public javax.swing.JLabel lblUserEmail;
    public javax.swing.JLabel lblUserName;
    public javax.swing.JLabel lblUserNumber;
    // End of variables declaration//GEN-END:variables
}
